spring.application.name=cart-service
server.port=${PORT:8082}

spring.datasource.url=jdbc:mysql://${DB_HOST:mithranmillets-muthuraman31-db0d.e.aivencloud.com}:${DB_PORT:24610}/cartdb?sslMode=REQUIRED
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5174}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.enabled=${EUREKA_ENABLED:true}
jwt.secret=${JWT_SECRET}
